### PR TITLE
added home, by rnihesh

### PR DESCRIPTION
**Pull request by rnihesh**
added Home.jsx , Home.css and did some changes

### CODE REVIEW

**Comment by Dipit12** [comment]
Send the screen recording of how the home page looks like, lemme see what I can do

**Comment by rnihesh** [comment]
if there is anything you want me to update, i'll do it, please assign me , so that i can complete hacktoberfest2024 badge collection 
https://github.com/user-attachments/assets/1b784b03-7336-497f-a70c-6b52cb9a6e70

if you are interested, i will also make login/signup page

**Comment by Dipit12** [comment]
Looks good, merged 😀

**Comment by rnihesh** [comment]
yeah thank you , but arent you participating in hactoberfest2024? , it shows , not participating, 
image

**Comment by rnihesh** [comment]
could you please consider this, 
image

**Pull request merged**
